name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: SERVER_HOST

    steps:
      - name: Debug secrets
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "User: ${{ secrets.EC2_USER }}"
          echo "Key length: ${#EC2_SSH_KEY}"
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/vite-app
            git pull origin main
            docker compose up -d --build
